import { Inject, Injectable, Logger } from '@nestjs/common';
import { ClientProxy } from '@nestjs/microservices';
import { lastValueFrom, timeout } from 'rxjs';
import { PrismaService } from '../prisma/prisma-service.service.ts';
import type { Alerts } from '../generated/prisma/client.ts';
import { PRODUCTS_EVENTS_CLIENT, PUBLISH_TIMEOUT_MS } from '../config/index.ts';
import { AlertEvents, type AlertEventPayload, type AlertNotification, type AlertProductSnapshot } from '../common/index.ts';
import { FindAlertsDto } from './dto/find-alerts.dto.ts';
import { syncLowStockAlert, type LowStockAlertChange } from './low-stock-alert.ts';

// Alerts are generated by syncLowStockAlert (low-stock-alert.ts) on every stock change,
// requested by ProductsService over RabbitMQ (AlertsClient -> AlertsController)
@Injectable()
export class AlertsService {
  private readonly logger = new Logger(AlertsService.name);

  constructor(
    private readonly prisma: PrismaService,
    @Inject(PRODUCTS_EVENTS_CLIENT) private readonly eventsClient: ClientProxy,
  ) { }

  async findAll({ organization_id, page, limit, estado }: FindAlertsDto) {
    const where = { organization_id, estado };

    const [total, alerts] = await this.prisma.withTenant(organization_id, async (tx) => [
      await tx.alerts.count({ where }),
      await tx.alerts.findMany({
        where,
        take: limit,
        skip: (page! - 1) * limit!,
        orderBy: { createdAt: 'desc' },
      }),
    ] as const);

    return {
      data: alerts.map((alert) => this.toAlertResponse(alert)),
      meta: {
        total,
        page,
        lastPage: Math.ceil(total / limit!),
      },
    };
  }

  // Reads the committed product so out-of-order requests never apply a stale snapshot.
  // The change is published after the commit, so the gateway never pushes a rolled back alert
  async syncLowStock(organization_id: string, product_id: number) {
    const { change, product } = await this.prisma.withTenant(organization_id, async (tx) => {
      const product = await tx.product.findUniqueOrThrow({ where: { id: product_id, organization_id } });
      return { change: await syncLowStockAlert(tx, product), product };
    });

    await this.publish(organization_id, change, { proveedor: product.proveedor, stock_minimo: product.stock_minimo });
  }

  // Best effort: the alert is already stored and GET /alerts returns it, so a failed
  // publish is only logged and never fails the stock change that triggered it
  private async publish(organization_id: string, change: LowStockAlertChange, product: AlertProductSnapshot) {
    if (!change) return;

    const pattern = change.type === 'created' ? AlertEvents.Created : AlertEvents.Resolved;
    const payload: AlertEventPayload = { organization_id, alert: this.toAlertResponse(change.alert), product };
    try {
      await lastValueFrom(this.eventsClient.emit(pattern, payload).pipe(timeout(PUBLISH_TIMEOUT_MS)), {
        defaultValue: undefined,
      });
    } catch (error) {
      this.logger.error(`Failed to publish ${pattern} for alert ${change.alert.id}: ${(error as Error)?.message ?? error}`);
    }
  }

  // proto-loader cannot serialize Date objects, so dates travel as ISO-8601 strings
  private toAlertResponse(alert: Alerts): AlertNotification {
    return {
      ...alert,
      createdAt: alert.createdAt.toISOString(),
      updatedAt: alert.updatedAt?.toISOString(),
    };
  }
}
