import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma-service.service.ts';
import type { Alerts } from '../generated/prisma/client.ts';
import { FindAlertsDto } from './dto/find-alerts.dto.ts';
import { syncLowStockAlert } from './low-stock-alert.ts';

// Alerts are generated by syncLowStockAlert (low-stock-alert.ts) on every stock change,
// requested by ProductsService over RabbitMQ (AlertsClient -> AlertsController)
@Injectable()
export class AlertsService {
  constructor(private readonly prisma: PrismaService) { }

  async findAll({ organization_id, page, limit, estado }: FindAlertsDto) {
    const where = { organization_id, estado };

    const [total, alerts] = await this.prisma.withTenant(organization_id, async (tx) => [
      await tx.alerts.count({ where }),
      await tx.alerts.findMany({
        where,
        take: limit,
        skip: (page! - 1) * limit!,
        orderBy: { createdAt: 'desc' },
      }),
    ] as const);

    return {
      data: alerts.map((alert) => this.toAlertResponse(alert)),
      meta: {
        total,
        page,
        lastPage: Math.ceil(total / limit!),
      },
    };
  }

  // Reads the committed product so out-of-order requests never apply a stale snapshot
  async syncLowStock(organization_id: string, product_id: number) {
    await this.prisma.withTenant(organization_id, async (tx) => {
      const product = await tx.product.findUniqueOrThrow({ where: { id: product_id, organization_id } });
      await syncLowStockAlert(tx, product);
    });
  }

  // proto-loader cannot serialize Date objects, so dates travel as ISO-8601 strings
  private toAlertResponse(alert: Alerts) {
    return {
      ...alert,
      createdAt: alert.createdAt.toISOString(),
      updatedAt: alert.updatedAt?.toISOString(),
    };
  }
}
