import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma-service.service.ts';
import type { Alerts } from '../generated/prisma/client.ts';
import { FindAlertsDto } from './dto/find-alerts.dto.ts';
import { syncLowStockAlert } from './low-stock-alert.ts';

// Alerts are generated by syncLowStockAlert (low-stock-alert.ts) on every stock change,
// requested by ProductsService over RabbitMQ (AlertsClient -> AlertsController)
@Injectable()
export class AlertsService {
  constructor(private readonly prisma: PrismaService) { }

  async findAll({ page, limit, estado }: FindAlertsDto) {
    const where = { estado };

    const total = await this.prisma.alerts.count({ where });

    const alerts = await this.prisma.alerts.findMany({
      where,
      take: limit,
      skip: (page! - 1) * limit!,
      orderBy: { createdAt: 'desc' },
    });

    return {
      data: alerts.map((alert) => this.toAlertResponse(alert)),
      meta: {
        total,
        page,
        lastPage: Math.ceil(total / limit!),
      },
    };
  }

  // Reads the committed product so out-of-order requests never apply a stale snapshot
  async syncLowStock(product_id: number) {
    await this.prisma.$transaction(async (tx) => {
      const product = await tx.product.findUniqueOrThrow({ where: { id: product_id } });
      await syncLowStockAlert(tx, product);
    });
  }

  // proto-loader cannot serialize Date objects, so dates travel as ISO-8601 strings
  private toAlertResponse(alert: Alerts) {
    return {
      ...alert,
      createdAt: alert.createdAt.toISOString(),
      updatedAt: alert.updatedAt?.toISOString(),
    };
  }
}
